Update others.yml

diff --git a/.github/workflows/others.yml b/.github/workflows/others.yml
--- a/.github/workflows/others.yml
+++ b/.github/workflows/others.yml
@@ -33,7 +33,6 @@ jobs:
         run: |
           dart pub remove dart_code_linter || true
           dart pub add --dev dart_code_linter
-
       - name: Run DCL
         id: dart_code_linter
         run: dart run dart_code_linter:metrics analyze . --reporter=html --output-directory=./html_reports
@@ -44,23 +43,11 @@ jobs:
 
       - name: Run Tests
         id: test
-        run: |
-          flutter test --coverage || true
-          ls -lh coverage/  # Debug: List coverage folder contents
-
-      - name: Verify Coverage File
-        run: |
-          if [ ! -f coverage/lcov.info ]; then
-            echo "No coverage data found! Exiting."
-            exit 1
-          fi
+        run: flutter test --coverage || true  # Continue even if tests fail
 
       - name: Generate Coverage Report
-        run: genhtml coverage/lcov.info --output-directory=coverage/lcov-report
-
-      - name: Debug Coverage Report Directory
-        run: ls -lh coverage/
-
+        run: |
+          genhtml coverage/lcov.info --output-directory=coverage/lcov-report
       - name: Install Allure CLI
         run: brew install allure
 
@@ -120,9 +107,6 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
-
-      - name: Debug Coverage Report Directory
-        run: ls -lh coverage/
 
       - name: Upload Coverage Report and Allure Report as Artifact
         uses: actions/upload-artifact@v4
